# -*- coding: utf-8 -*-
"""python_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hugtlt_-iCI9FJs3VZtaA2AdgL0VMd6n

**What is program** :
A program is a set of instructions written in a programming language that tells a computer what to do. These instructions guide the computer to perform specific tasks such as calculations, data processing, displaying information, or controlling devices. A program works step by step, following the logic defined by the programmer, to solve a problem or complete a task.

**Variable** :
A variable is a named storage location in a computer program used to store data that can change while the program is running. The value stored in a variable can be updated, used in calculations, or displayed as output. Variables help programs remember and work with information such as numbers, text, or results of operations.**bold text**
"""

# VARIABLE
length = 15
print(length)

price = [10,45,56,68,345]
print(price)

name,qut,price = 'clock',3,800
print(name)
print(price)
print(qut)

a,b,c = 1,1,1
print(id(a),id(b),id(c))

"""**DYNAMICALLY TYPED** : A dynamically typed language is a programming language in which you do not need to declare the data type of a variable in advance. The type of the variable is decided at runtime, based on the value assigned to it, and it can change during program execution."""

var = 15
print(type(var))

new = 'dynamic'
print(type(new))

l = [2,5,7,7]
print(type(l))